/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import * as msRest from "@azure/ms-rest-js";
import * as Models from "./models";
import * as Mappers from "./models/mappers";
import * as Parameters from "./models/parameters";
import { DidacticalEnigmaRestApiContext } from "./didacticalEnigmaRestApiContext";

class DidacticalEnigmaRestApi extends DidacticalEnigmaRestApiContext {
  /**
   * Initializes a new instance of the DidacticalEnigmaRestApi class.
   * @param [options] The parameter options
   */
  constructor(options?: Models.DidacticalEnigmaRestApiOptions) {
    super(options);
  }

  /**
   * @param [options] The optional parameters
   * @returns Promise<Models.ListRadicalsResponse>
   */
  listRadicals(options?: msRest.RequestOptionsBase): Promise<Models.ListRadicalsResponse>;
  /**
   * @param callback The callback
   */
  listRadicals(callback: msRest.ServiceCallback<string[]>): void;
  /**
   * @param options The optional parameters
   * @param callback The callback
   */
  listRadicals(options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<string[]>): void;
  listRadicals(options?: msRest.RequestOptionsBase | msRest.ServiceCallback<string[]>, callback?: msRest.ServiceCallback<string[]>): Promise<Models.ListRadicalsResponse> {
    return this.sendOperationRequest(
      {
        options
      },
      listRadicalsOperationSpec,
      callback) as Promise<Models.ListRadicalsResponse>;
  }

  /**
   * @param [options] The optional parameters
   * @returns Promise<Models.SelectRadicalsResponse>
   */
  selectRadicals(options?: Models.DidacticalEnigmaRestApiSelectRadicalsOptionalParams): Promise<Models.SelectRadicalsResponse>;
  /**
   * @param callback The callback
   */
  selectRadicals(callback: msRest.ServiceCallback<Models.KanjiLookupResult>): void;
  /**
   * @param options The optional parameters
   * @param callback The callback
   */
  selectRadicals(options: Models.DidacticalEnigmaRestApiSelectRadicalsOptionalParams, callback: msRest.ServiceCallback<Models.KanjiLookupResult>): void;
  selectRadicals(options?: Models.DidacticalEnigmaRestApiSelectRadicalsOptionalParams | msRest.ServiceCallback<Models.KanjiLookupResult>, callback?: msRest.ServiceCallback<Models.KanjiLookupResult>): Promise<Models.SelectRadicalsResponse> {
    return this.sendOperationRequest(
      {
        options
      },
      selectRadicalsOperationSpec,
      callback) as Promise<Models.SelectRadicalsResponse>;
  }

  /**
   * @param [options] The optional parameters
   * @returns Promise<Models.GetWordInformationResponse>
   */
  getWordInformation(options?: Models.DidacticalEnigmaRestApiGetWordInformationOptionalParams): Promise<Models.GetWordInformationResponse>;
  /**
   * @param callback The callback
   */
  getWordInformation(callback: msRest.ServiceCallback<Models.WordInfo[][]>): void;
  /**
   * @param options The optional parameters
   * @param callback The callback
   */
  getWordInformation(options: Models.DidacticalEnigmaRestApiGetWordInformationOptionalParams, callback: msRest.ServiceCallback<Models.WordInfo[][]>): void;
  getWordInformation(options?: Models.DidacticalEnigmaRestApiGetWordInformationOptionalParams | msRest.ServiceCallback<Models.WordInfo[][]>, callback?: msRest.ServiceCallback<Models.WordInfo[][]>): Promise<Models.GetWordInformationResponse> {
    return this.sendOperationRequest(
      {
        options
      },
      getWordInformationOperationSpec,
      callback) as Promise<Models.GetWordInformationResponse>;
  }
}

// Operation Specifications
const serializer = new msRest.Serializer(Mappers);
const listRadicalsOperationSpec: msRest.OperationSpec = {
  httpMethod: "GET",
  path: "radicals/list",
  responses: {
    200: {
      bodyMapper: {
        serializedName: "parsedResponse",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "String"
            }
          }
        }
      }
    },
    default: {}
  },
  serializer
};

const selectRadicalsOperationSpec: msRest.OperationSpec = {
  httpMethod: "GET",
  path: "radicals/select",
  queryParameters: [
    Parameters.radical
  ],
  responses: {
    200: {
      bodyMapper: Mappers.KanjiLookupResult
    },
    default: {}
  },
  serializer
};

const getWordInformationOperationSpec: msRest.OperationSpec = {
  httpMethod: "GET",
  path: "wordInfo",
  queryParameters: [
    Parameters.fullText
  ],
  responses: {
    200: {
      bodyMapper: {
        serializedName: "parsedResponse",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Sequence",
              element: {
                type: {
                  name: "Composite",
                  className: "WordInfo"
                }
              }
            }
          }
        }
      }
    },
    default: {}
  },
  serializer
};

export {
  DidacticalEnigmaRestApi,
  DidacticalEnigmaRestApiContext,
  Models as DidacticalEnigmaRestApiModels,
  Mappers as DidacticalEnigmaRestApiMappers
};
