/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

import { ServiceClientOptions } from "@azure/ms-rest-js";
import * as msRest from "@azure/ms-rest-js";

/**
 * An interface representing WordInfo.
 */
export interface WordInfo {
  text?: string;
  dictionaryForm?: string;
  reading?: string;
}

/**
 * An interface representing DidacticalEnigmaRestApiOptions.
 */
export interface DidacticalEnigmaRestApiOptions extends ServiceClientOptions {
  baseUri?: string;
}

/**
 * Optional Parameters.
 */
export interface DidacticalEnigmaRestApiGetWordInformationOptionalParams extends msRest.RequestOptionsBase {
  fullText?: string;
}

/**
 * Contains response data for the listRadicals operation.
 */
export type ListRadicalsResponse = Array<string> & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: string[];
    };
};

/**
 * Contains response data for the getWordInformation operation.
 */
export type GetWordInformationResponse = Array<WordInfo[]> & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: WordInfo[][];
    };
};
