/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

import * as msRest from "@azure/ms-rest-js";


export const WordInfo: msRest.CompositeMapper = {
  serializedName: "WordInfo",
  type: {
    name: "Composite",
    className: "WordInfo",
    modelProperties: {
      text: {
        serializedName: "text",
        type: {
          name: "String"
        }
      },
      dictionaryForm: {
        serializedName: "dictionaryForm",
        type: {
          name: "String"
        }
      },
      reading: {
        serializedName: "reading",
        type: {
          name: "String"
        }
      }
    }
  }
};
