/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

import * as msRest from "@azure/ms-rest-js";


export const KanjiLookupResult: msRest.CompositeMapper = {
  serializedName: "KanjiLookupResult",
  type: {
    name: "Composite",
    className: "KanjiLookupResult",
    modelProperties: {
      kanji: {
        serializedName: "kanji",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "String"
            }
          }
        }
      },
      possibleRadicals: {
        serializedName: "possibleRadicals",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "String"
            }
          }
        }
      }
    }
  }
};

export const WordInfo: msRest.CompositeMapper = {
  serializedName: "WordInfo",
  type: {
    name: "Composite",
    className: "WordInfo",
    modelProperties: {
      text: {
        serializedName: "text",
        type: {
          name: "String"
        }
      },
      dictionaryForm: {
        serializedName: "dictionaryForm",
        type: {
          name: "String"
        }
      },
      reading: {
        serializedName: "reading",
        type: {
          name: "String"
        }
      }
    }
  }
};
