/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

import * as msRest from "@azure/ms-rest-js";


export const DataSourceInformation: msRest.CompositeMapper = {
  serializedName: "DataSourceInformation",
  type: {
    name: "Composite",
    className: "DataSourceInformation",
    modelProperties: {
      identifier: {
        required: true,
        serializedName: "identifier",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const DataSourceParseRequest: msRest.CompositeMapper = {
  serializedName: "DataSourceParseRequest",
  type: {
    name: "Composite",
    className: "DataSourceParseRequest",
    modelProperties: {
      requestedDataSources: {
        serializedName: "requestedDataSources",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "String"
            }
          }
        }
      },
      id: {
        serializedName: "id",
        type: {
          name: "String"
        }
      },
      position: {
        serializedName: "position",
        type: {
          name: "Number"
        }
      }
    }
  }
};

export const DataSourceParseResponse: msRest.CompositeMapper = {
  serializedName: "DataSourceParseResponse",
  type: {
    name: "Composite",
    className: "DataSourceParseResponse",
    modelProperties: {
      context: {
        serializedName: "context",
        type: {
          name: "String"
        }
      },
      error: {
        serializedName: "error",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const KanjiLookupResult: msRest.CompositeMapper = {
  serializedName: "KanjiLookupResult",
  type: {
    name: "Composite",
    className: "KanjiLookupResult",
    modelProperties: {
      kanji: {
        required: true,
        serializedName: "kanji",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "String"
            }
          }
        }
      },
      possibleRadicals: {
        required: true,
        serializedName: "possibleRadicals",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "String"
            }
          }
        }
      },
      usedRadicals: {
        required: true,
        serializedName: "usedRadicals",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "String"
            }
          }
        }
      }
    }
  }
};

export const WordInfo: msRest.CompositeMapper = {
  serializedName: "WordInfo",
  type: {
    name: "Composite",
    className: "WordInfo",
    modelProperties: {
      text: {
        required: true,
        serializedName: "text",
        type: {
          name: "String"
        }
      },
      dictionaryForm: {
        required: true,
        serializedName: "dictionaryForm",
        type: {
          name: "String"
        }
      },
      reading: {
        required: true,
        serializedName: "reading",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const WordInfoResponse: msRest.CompositeMapper = {
  serializedName: "WordInfoResponse",
  type: {
    name: "Composite",
    className: "WordInfoResponse",
    modelProperties: {
      wordInformation: {
        required: true,
        serializedName: "wordInformation",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Sequence",
              element: {
                type: {
                  name: "Composite",
                  className: "WordInfo"
                }
              }
            }
          }
        }
      },
      identifier: {
        required: true,
        serializedName: "identifier",
        type: {
          name: "String"
        }
      }
    }
  }
};
