/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import * as msRest from "@azure/ms-rest-js";

export const fullText: msRest.OperationQueryParameter = {
  parameterPath: [
    "options",
    "fullText"
  ],
  mapper: {
    serializedName: "fullText",
    type: {
      name: "String"
    }
  }
};
export const identifier: msRest.OperationQueryParameter = {
  parameterPath: [
    "options",
    "identifier"
  ],
  mapper: {
    serializedName: "identifier",
    type: {
      name: "String"
    }
  }
};
export const query: msRest.OperationQueryParameter = {
  parameterPath: [
    "options",
    "query"
  ],
  mapper: {
    serializedName: "query",
    type: {
      name: "String"
    }
  }
};
export const sort: msRest.OperationQueryParameter = {
  parameterPath: [
    "options",
    "sort"
  ],
  mapper: {
    serializedName: "sort",
    type: {
      name: "String"
    }
  }
};
