/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import * as msRest from "@azure/ms-rest-js";

export const fullText: msRest.OperationQueryParameter = {
  parameterPath: [
    "options",
    "fullText"
  ],
  mapper: {
    serializedName: "fullText",
    type: {
      name: "String"
    }
  }
};
export const radical: msRest.OperationQueryParameter = {
  parameterPath: [
    "options",
    "radical"
  ],
  mapper: {
    serializedName: "radical",
    type: {
      name: "String"
    }
  }
};
